# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: rnaseq-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
# required software dependencies here
# conda-forge

# bioconda
  - bioconda::fastqc=0.11.9
  - bioconda::salmon=1.8.0
  - bioconda::multiqc=1.12